name: ${project.artifactId}
version: ${project.version}
api-version: 1.14
description: ${project.description}
author: mattboy9921 (mattboy9921@aim.com)
main: net.mattlabs.crewchat.CrewChat

permissions:
  crewchat.subscribe.channel:
    description: Allows player to subscribe to [channel].
  crewchat.unsubscribe.channel:
    description: Allows player to unsubscribe to [channel].
  crewchat.active.channel:
    description: Allows player to set [channel] as active channel.
  crewchat.speak.channel:
    description: Allows player to speak in [channel].
  crewchat.reload:
    description: Allows player to reload configuration.
  crewchat.chat.info:
    description: Allows player to run /chat info.