name: ${project.artifactId}
version: ${project.version}
api-version: 1.13
description: ${project.description}
author: mattboy9921 (mattboy9921@aim.com)
main: net.mattlabs.crewchat.CrewChat
softdepend:
  - DiscordSRV
  - Vault
loadbefore:
  - DiscordSRV

permissions:
  crewchat.chat.subscribe.channel:
    description: Allows player to subscribe to [channel].
  crewchat.chat.unsubscribe.channel:
    description: Allows player to unsubscribe to [channel].
  crewchat.chat.switch.channel:
    description: Allows player to switch to [channel] as active channel.
  crewchat.speak.channel:
    description: Allows player to speak in [channel].
  crewchat.reload:
    description: Allows player to reload configuration.
  crewchat.chat.info:
    description: Allows player to run /chat info.